# <center> CV2 Face detection</center>

In [1]:
# Importing python modules
import cv2 
import numpy as np


In [ ]:
face_cascade = cv2.CascadeClassifier('./models/haarcascades/haarcascade_frontalface_default.xml')

In [ ]:
# Read image and convert into the gray color
img = cv2.imread('./images/face-image.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


In [ ]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

print(faces)

if faces is ():
    print('No face found')

for x, y, w, h in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (127,0,255), 2)
    cv2.imshow('Face Detection', img)
    cv2.waitKey(0)
    

In [ ]:
cv2.imwrite('./images/face-gray-image.jpg', gray)

## Eye recognization

In [2]:
eye_cascade = cv2.CascadeClassifier('./models/haarcascades/haarcascade_eye.xml')
face_cascade = cv2.CascadeClassifier('./models/haarcascades/haarcascade_frontalface_default.xml')

In [8]:

# Read image and convert into the gray color
img = cv2.imread('./images/face-image.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

face = face_cascade.detectMultiScale(gray, 1.3, 5)

print(face)

if face is ():
    print('No face found')

for x, y, w, h in face:
    cv2.rectangle(img, (x, y), (x+w, y+h), (127,0,255), 2)
    cv2.imshow('Face Detection', img)
    cv2.waitKey(0)
    
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    
    eye = eye_cascade.detectMultiScale(roi_gray)
    print(eye)
    for ex, ey, ew, eh in eye:
        cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (255, 255, 0), 2)
        cv2.imshow('Eye Detection', img)
        cv2.waitKey(0)
        
cv2.destroyAllWindows()


[[ 97  56 281 281]]
[[ 56  76  66  66]
 [157  81  57  57]]


# 